### ISSUE TITLE
[BUG]✘ [ERROR] Could not resolve "@aws-lambda-powertools/tracer" and "@aws-lambda-powertools/logger" when deploying

### ISSUE THREAD

**Issue by dexter-cc** [aws-samples/websocket-chat-application#4]
**Problems:**

Encounterred below errors on Lambda Powertools when trying to deploy.

`✘ [ERROR] Could not resolve "@aws-lambda-powertools/tracer"

    asset-input/handlers/websocket/authorizer.ts:5:23:
      5 │ import { Tracer } from '@aws-lambda-powertools/tracer';
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@aws-lambda-powertools/tracer" as external to exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "@aws-lambda-powertools/logger"

    asset-input/handlers/websocket/authorizer.ts:6:23:
      6 │ import { Logger } from '@aws-lambda-powertools/logger';
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@aws-lambda-powertools/logger" as external to exclude it from the bundle, which will remove this error.

✘ [ERROR] Could not resolve "aws-jwt-verify"

    asset-input/handlers/websocket/authorizer.ts:8:35:
      8 │ import { CognitoJwtVerifier } from "aws-jwt-verify";
        ╵                                    ~~~~~~~~~~~~~~~~`

`/infrastructure/resources/handlers/websocket/` files are complaining about `@tracer.*` decorator and `aws-lambda` not found error.  The problems seem to be Powertools related but no errors on`Metrics` . Thanks

**Versions**
```
    "aws-jwt-verify": "^3.1.0",
    "aws-lambda": "^1.0.7",
    "@aws-lambda-powertools/logger": "^1.0.2",
    "@aws-lambda-powertools/tracer": "^1.0.2",
```

**Comment by santatamas** [comment]
Hi! 

Thank you for taking the time to report this issue. The cause was a missing build step (as I had previously pre-compiled the lambda handlers). I included the module dependencies in the CDK stack definitions. I've also added esbuild as a dependency, so the CDK build won't rely on docker containers anymore.

Please pull the latest version and try again :) If you encounter further issues, please don't hesitate to get in touch! 
Your feedback is greatly appreciated.

Cheers,
Tamas

**Comment by dexter-cc** [comment]
Awesome, it's working now.  thanks @santatamas
